---
# tasks file for glusterfs

- name: oc login
  shell: oc login -u system:admin

- name: swtich project
  shell: oc project gluster-app-storage

- name: Get Heketi pod
  shell: kubectl -n {{ namespace }} get pods | grep heketi | awk '{print $1}'
  register: heketi_pod

- name: Get Cluster information
  shell: kubectl -n {{ namespace }} exec {{ heketi_pod.stdout }} -- heketi-cli  cluster list | grep -oP "^Id:\s\K([A-Za-z0-9]*)"
  register: cluster_id

- name: Add node to cluster
  shell: kubectl -n {{ namespace }} exec {{ heket_pod.stdout }} -- heketi-cli node add --zone={{zone}} --cluster={{ cluster_id.stdout }} --management-host-name={{ glusterfs_hostname }} --storage-host-name={{ glusterfs_ip }}
  register: output
  failed_when: ('used by node' not in output.stdout)

- name: Get Topology info 
  shell: kubectl -n {{ namespace }} exec {{ heket_pod.stdout }} -- heketi-cli topology info --json=true | jq '.clusters[0].nodes[] | select(.zone=={{zone}}).id' 
  register: node_id

- name: Add device to node
  shell: kubectl -n {{ namespace }} exec {{ heketi_pod.stdout }} -- heketi-cli device add --name={{item}} --node={{ node_id.stdout }}
  with_items: glusterfs_devices

- name: Enable node
  shell: kubectl -n {{ namespace }} exec {{ heketi_pod.stdout }} -- heketi-cli enable {{ node_id.stdout }}
  with_items: glusterfs_devices